### ISSUE TITLE
position fixed

### ISSUE THREAD

**Issue by jernejrostan** [jmeas/prevent-scroll#32]
Hi,

I found one issue with position fixed on **html** element. 
If you have navigation bar on top that has fixed positon it crashes that navigation bar.

Any ideas how to solve that?

Nice plugin btw!

**Comment by jernejrostan** [comment]
Fixed it already :) added top: 0px; and left: 0px; to other elements :)

**Comment by jamesplease** [comment]
Good to hear! I'll close this issue then. Let me know if you have any other issues.
